### ISSUE TITLE
clarification of yubihsm 2 support

### ISSUE THREAD

**Issue by thedavidmeister** [Consensys/doc.web3signer#181]
The docs state

> Web3Signer supports using the device as a secure key storage only.

For yubihsm 2 https://docs.web3signer.consensys.net/how-to/store-keys-hsm/yubihsm2

But it also states

> Web3Signer can sign payloads using private keys stored in the [YubiHSM 2 hardware security module](https://developers.yubico.com/YubiHSM2/).

So what does it mean that the device is "only" secure key storage, what else would it be doing?

I don't understand the implied limitations of the wording in this document.

**Comment by usmansaleem** [comment]
@thedavidmeister One of the YubiHSM feature is that it supports signing of data using RSA based private keys stored in it, however, Web3Signer uses BLS based private keys which are not supported by YubiHSM. Hence we are only using YubiHSM's secure data storage feature and the actual signing of data is performed within Web3Signer. Hope this helps.

**Comment by thedavidmeister** [comment]
@usmansaleem hmm, does that mean that the private key is exported from the HSM into web3signer?

how else can you use it to sign data?

**Comment by usmansaleem** [comment]
@thedavidmeister that is correct, regardless of the method, web3signer loads eventually all private keys in memory to sign the data locally sent by consensus clients. YubiHSM was a proof-of-concept integration and there are discussions to deprecate its support in Web3Signer in future.

**Comment by thedavidmeister** [comment]
@usmansaleem thanks for the clarification, you just saved me wasting $650

the docs should state if something expensive like a HSM is deprecated

are there any other options for HW backed private keys that allow signing on the device rather than being loaded into memory?

**Comment by thedavidmeister** [comment]
@usmansaleem one thing i'm wondering, is what the behaviour would be in case of a reboot with and without the yubiHSM

i'm concerned that if there's some encrypted file on disk storing private keys that i'll have to physically enter a password on reboot so that the signer can access them, i'm wondering if the yubiHSM avoids this?

**Comment by usmansaleem** [comment]
@thedavidmeister currently there are no hardware devices out there that support both storage and signing of BLS private keys.

Web3Signer reads all the passwords from text files. YubiHSM also need a password for authentication and that is also read from a file by Web3Signer. Keys are read at web3signer startup and stay in memory while web3signer is running.

Our enterprise clients usually use AWS, Azure and Hashicorp when dealing with hundreds or thousands of private keys as it provides both security and auditability. Encrypted key format is useful with lesser number of keys because the decryption process takes time. 

Azure and AWS mode also provide support for managed authentication/identity when running Web3Signer in Azure or AWS which eliminates the need of password when accessing vault/secrets manager.

Since Web3Signer is meant to sit behind Teku (or consensus client), the security is driven from using appropriate firewall rules. Web3Signer's server ports are not meant to exposed for direct access on internet (unlike Teku, for example). In addition to that, the file permissions are used to isolate process access to the password/keystore files.

Hope this helps.

**Comment by thedavidmeister** [comment]
@usmansaleem yeah it helps, i'm not using other people's computers so that's why i was asking about hardware

in that case i'll probably just setup a box with no exposed ports like you say, and not worry about a yubikey

**Comment by usmansaleem** [comment]
@thedavidmeister feel free to reach out on our Discord channel (https://discord.gg/consensys) if you need further information. Also, we (the developers) more actively monitor https://github.com/Consensys/web3signer/issues. This doc repo is primarily used by the docs team.
